### ISSUE TITLE
[Minor] remove spaces in bookmarklet

### ISSUE THREAD

**Issue by JTBrinkmann** [extplug/ExtPlug#25]
The bookmarklet currently has two spaces `javascript:(function(){ $.getScript('https://extplug.github.io/ExtPlug/extplug.js') }());`
I noticed that when copying the bookmarklet, Firefox URI encodes it (turning the spaces into `%20`), but when pasting URI encoded bookmarklets into Chrome's URL bar (and pressing Enter), it complains about invalid JavaScript. `Uncaught SyntaxError: Unexpected token %`

This is an edge case, as it involves copying the bookmarklet from one browser and pasting it into the URL bar of another, specifically, but it could also be reproduced by e.g. sending the (encoded) bookmarklet via chat, for example. It primarily affects users who want to try out ExtPlug without adding the bookmarklet to their bookmarks, so it could negatively affect the **first impression**.

It's easy to fix, as it simply involves removing the spaces from the bookmarklet. Existing users wouldn't necessarily have to update their bookmarklets.
Personally I would suggest removing the IIFE function wrapper from the bookmarklet completely, as it serves _no benefit_ to begin with.

Steps to reproduce:
1. (in Firefox) go to http://extplug.github.io/
2. right click bookmarklet and copy URL ("Copy Link Location")
3. (in Chrome) go to https://plug.dj/
4. select URL bar and paste
5. (prepend URL with "javascript:" as it gets cut off; press enter)

**Comment by JTBrinkmann** [comment]
hmm, thinking about it, this should've been reported to ExtPlug/extplug.github.io, maybe :I

**Comment by goto-bus-stop** [comment]
Nice catch. Thanks! :blush:
