### ISSUE TITLE
Some plugins won't disable, none uninstalls

### ISSUE THREAD

**Issue by WiBla** [extplug/ExtPlug#46]
As you can see from this gif:
![2016-11-11_22-20-28](https://cloud.githubusercontent.com/assets/11421812/20230645/451641f2-a85d-11e6-9fee-fd60269dfd17.gif)
Some plugins won't disable, not only that but as far as I know, none of them are uninstallable, when I reload, they are loaded again.
I think this is due to the localStorage but I can't say for sure.

**Comment by goto-bus-stop** [comment]
I think disabling could fail silently if there was an error in the plugin's `disable()` handler. I don't know why uninstalling wasn't working, but it works on master and in the next release.

Thanks for the report!
